# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
os: linux
dist: bionic

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libgsl-dev libv8-dev
  - git lfs pull
  
jobs:
  include:
    - stage: notebook one
      script:
        # information about the build
        - uname -a
        - free -m
        - df -h
        - ulimit -a
        # background sleep loop outputting something every 9 minutes to avoid kill
        - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
        # render the r notebook one
        - R -f tests/render_notebook_one.R
        # Killing background sleep loop
        - kill %1
        #information about the build
        - uname -a
        - free -m
        - df -h
        - ulimit -a
    - stage: notebook two
      script:
        # information about the build
        - uname -a
        - free -m
        - df -h
        - ulimit -a
        # create background sleep loop
        - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
        # render the r notebook one
        - R -f tests/render_notebook_two.R
        # Killing background sleep loop
        - kill %1
        #information about the build
        - uname -a
        - free -m
        - df -h
        - ulimit -a
        