# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
sudo: required
cache: packages
dist: xenial

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libgsl-dev libv8-dev
  - git lfs pull

script: 
  # Output something every 10 minutes or Travis kills the job
  - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - R -f tests/render_rmds.R
  # Killing background sleep loop
  - kill %1
  - df -h
