---
title: "Segregation Components Paper Code"
author: "Katherine Rose Wolf"
date: "June 12, 2019"
output: html_document
---

# CODE SETUP

```{r load packages}

library(rmarkdown)
library(knitr)
library(plyr)
library(data.table)
library(Hmisc)
library(extrafontdb)
library(extrafont)
library(NADA)
library(grid)
library(gridExtra)
library(lattice)
library(tmap)
library(sf)
library(tidycensus)
library(tigris)
library(rgeos)
library(sjPlot)
library(stargazer)
library(readxl)
library(tidyverse)
library(totalcensus)

```


```{r rmarkdown options, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```


```{r census api key and options for tidycensus}

# install the census api key
census_api_key("eae31d12c8d9c2c9ee288e096e0c03830744aaef", 
               install = TRUE, 
               overwrite = TRUE)

readRenviron("~/.Renviron")

# have tidycensus store old shapefiles for future use
options(tigris_use_cache = TRUE)

```


```{r functions for later use}

# function to convert column names to snake case
column_name_fixer <-
  function(tibble) {
  new_names <-
    tibble %>%
    colnames() %>%  # gets the column names from the tibble
    tolower() %>%  # converts the column names to lowercase
    {gsub(" ", "_", .)}  # replaces spaces with "_"
  colnames(tibble) <-
    new_names  # rename the columns in the original tibble
  return(tibble)
  }

# create function that downloads files
file_downloader <-
  function(desired_filename_as_string, 
           web_address_as_string, 
           folder_as_string) {
    
    path <-  # specify the file path
      file.path(
        folder_as_string,
        desired_filename_as_string) 
    
    if(!file.exists(path))  # checks if file exists already
      download.file(url = web_address_as_string,  # if not, downloads/saves file
                    destfile = path, 
                    mode = "wb")
  }

```

# CREATE SUBDIRECTORIES

```{r create subdirectories}
if(!dir.exists("raw_data"))
  dir.create("raw_data")

if(!dir.exists("intermediate_data"))
  dir.create("intermediate_data")
```

# LOAD NECESSARY FILES

```{r census data, results = "hide"}

# last updated by census bureau 	19-Jul-2012 07:01	391M

if(
  !file.exists(
    file.path(
      "intermediate_data", 
      "census_data_shapefile.rdata"
      )
    )
) {
  # download zip file of census dp1 shapefiles
  file_downloader(
    desired_filename_as_string = "tract_2010_census_dp1.zip",
    web_address_as_string = 
      "http://www2.census.gov/geo/tiger/TIGER2010DP1/Tract_2010Census_DP1.zip", 
    folder_as_string = "raw_data"
    )

# unzip it to the intermediate file directory
  unzip(
    file.path(
      "raw_data", 
      "tract_2010_census_dp1.zip"), 
    exdir = "intermediate_data")

  # read the shapefile
  census_data_shapefile <- 
    read_sf(
      file.path(
        "intermediate_data", 
        "Tract_2010Census_DP1.shp"
        )
      )
  
  # fix column names
  census_data_shapefile <-
    column_name_fixer(
      census_data_shapefile
    )


  # save the shapefile
  save(
    census_data_shapefile,
    file = file.path(
      "intermediate_data", 
      "census_data_shapefile.rdata"
    )
  )

  # remove the shapefile from memory
  rm(census_data_shapefile)
  gc()
}

```


```{r ruca data}

if(
  !file.exists(
    file.path(
      "intermediate_data", 
      "ruca_2010.rdata"
      )
    )
  ) {
  file_downloader(
    desired_filename_as_string = "ruca_2010_raw.xlsx", 
    web_address_as_string = 
      "https://www.ers.usda.gov/webdocs/DataFiles/53241/ruca2010.xlsx?v=0", 
    folder_as_string = "raw_data"
    )

  ruca_2010_raw <- 
    read_xlsx(
      file.path(
        "raw_data", 
        "ruca_2010_raw.xlsx"
        )
      )
  
  # fix column names
  ruca_2010 <-
    column_name_fixer(
      ruca_2010_raw
    )

  # save the shapefile
  save(
    ruca_2010,
    file = file.path(
      "intermediate_data", 
      "ruca_2010.rdata"
    )
  )

  # remove the shapefile from memory
  rm(ruca_2010_raw, ruca_2010)
  gc()
}

```


```{r speciation parameter codes, results = "hide"}

if(
  !file.exists(
    file.path(
      "intermediate_data", 
      "speciation_parameter_codes.rdata"
      )
    )
  ) {
  
  # download the speciation paramter codes
  file_downloader(
    desired_filename_as_string = "speciation_parameter_codes.csv",
    web_address_as_string = "https://aqs.epa.gov/aqsweb/documents/codetables/methods_speciation.csv", 
    folder_as_string = "raw_data"
    )

  # read the parameter codes into memory
  speciation_parameter_codes <- 
    read_csv(
      file.path("raw_data", 
                "speciation_parameter_codes.csv"
                )
    )
  
  # fix column names
  speciation_parameter_codes <-
    column_name_fixer(
     speciation_parameter_codes
    )

  # save the rdata file
  save(
    speciation_parameter_codes,
    file = file.path(
      "intermediate_data", 
      "speciation_parameter_codes.rdata"
    )
  )

  # remove the rdata from memory
  rm(speciation_parameter_codes)
  gc()
}

```


```{r make parameter and species lists}

load(
  file = 
    file.path(
      "intermediate_data", 
      "speciation_parameter_codes.rdata"
      )
)

# make a list of all the species and their codes
species_and_codes <- 
  speciation_parameter_codes %>% 
  select(parameter, parameter_code) %>% 
  distinct

# make a list of the organic carbon species and codes
organic_carbon_rows <- 
  species_and_codes %>% 
  filter(str_detect(parameter, "OC"))

# make a numeric vector of the organic carbon species and codes
organic_carbon_codes <-
  organic_carbon_rows %>% 
  select(parameter_code) %>% 
  pull()

save(
  species_and_codes, 
  file = 
    file.path(
      "intermediate_data", 
      "species_and_codes.rdata"
    )
  )

save(
  organic_carbon_codes, 
  file = 
    file.path(
      "intermediate_data", 
      "organic_carbon_codes.rdata"
    )
  )

# remove created data from memory
rm(
  organic_carbon_codes, 
  speciation_parameter_codes,
  species_and_codes)
gc()

```


## air pollution data files

```{r pm2.5 total frm}

if(
  !file.exists(
    file.path(
      "intermediate_data", 
      "big_pm_25_frm_tibble.rdata"
      )
    )
  ) {

  # make list of files to download
  pm_25_frm_files <- 
    c("https://aqs.epa.gov/aqsweb/airdata/daily_88101_2005.zip",
      "https://aqs.epa.gov/aqsweb/airdata/daily_88101_2006.zip",
      "https://aqs.epa.gov/aqsweb/airdata/daily_88101_2007.zip",
      "https://aqs.epa.gov/aqsweb/airdata/daily_88101_2008.zip",
      "https://aqs.epa.gov/aqsweb/airdata/daily_88101_2009.zip",
      "https://aqs.epa.gov/aqsweb/airdata/daily_88101_2010.zip",
      "https://aqs.epa.gov/aqsweb/airdata/daily_88101_2011.zip",
      "https://aqs.epa.gov/aqsweb/airdata/daily_88101_2012.zip",
      "https://aqs.epa.gov/aqsweb/airdata/daily_88101_2013.zip",
      "https://aqs.epa.gov/aqsweb/airdata/daily_88101_2014.zip",
      "https://aqs.epa.gov/aqsweb/airdata/daily_88101_2015.zip")
  
  
  # make a list of filenames for the downloaded data using the above filenames
  list_of_pm_25_frm_zip_filenames <-  # make list of what the filenames will be
    map_chr(pm_25_frm_files,  # witness the `map` function
            str_extract, 
            "daily_.+\\.zip")   # witness the regular expression!
  
  # download the files
  map2(list_of_pm_25_frm_zip_filenames, 
       pm_25_frm_files, 
       file_downloader, 
       folder_as_string = "raw_data")
  
  # unzip all the files and save them to disk
  map(
    file.path(
      "raw_data",
      list_of_pm_25_frm_zip_filenames
      ),
    unzip,
    exdir = "intermediate_data"
    )
  
  # replace ".zip" with ".csv" in list_of_pm_25_frm_zip_filenames
  list_of_pm_25_frm_csv_filenames <-
    map(list_of_pm_25_frm_zip_filenames,
        str_replace,
        "zip",
        "csv")
  
  # make list of tibble names by removing the ".zip" extension
  list_of_pm_25_frm_tibble_names <-
    map(list_of_pm_25_frm_zip_filenames,
        str_replace,
        ".zip",
        "")
  
  # read .csv files into tibbles!
  if(
    !file.exists(
      file.path(
        "intermediate_data",
        "list_of_pm_25_frm_tibbles.rdata"
        )
      )
    ) {  # checks if tibbles already exist
    list_of_pm_25_frm_tibbles <-  # if not reads .csv files into tibbles
      map(
        file.path(
          "intermediate_data",
          list_of_pm_25_frm_csv_filenames),
        read_csv
        )
    names(list_of_pm_25_frm_tibbles) <-  # names the tibbles
      list_of_pm_25_frm_tibble_names
    save(
      list_of_pm_25_frm_tibbles,  # saves the tibbles to disk to avoid doing this again
      file = file.path(
        "intermediate_data",
        "list_of_pm_25_frm_tibbles.rdata"
        )
      )
    
  } else {
      load(
        file = file.path(
        "intermediate_data",
        "list_of_pm_25_frm_tibbles.rdata"
        )
        )  # loads the tibbles if they don't already exist
  }
  
  # fix column names
  list_of_pm_25_frm_tibbles <-
    map(list_of_pm_25_frm_tibbles,
        column_name_fixer)
  
  # combine air data tibbles into one big tibble
  big_pm_25_frm_tibble <-
    bind_rows(list_of_pm_25_frm_tibbles)
  
  # remove non-needed columns
  big_pm_25_frm_tibble <- 
    big_pm_25_frm_tibble %>%
    select(-c(
      pollutant_standard, 
      units_of_measure, 
      aqi, 
      method_name, 
      local_site_name, 
      address, 
      county_name)
      )
  
  # save all air data to disk
  save(
      big_pm_25_frm_tibble,  # saves the tibbles to disk to avoid doing this again
      file = file.path(
        "intermediate_data",
        "big_pm_25_frm_tibble.rdata"
        )
      )
  
  # memory and disk clearance --------------------------------------------------
  
  # delete individual .csv files from disk
  map(
    file.path(
      "intermediate_data",
      list_of_pm_25_frm_csv_filenames
      ),
    file.remove
    )
  
  # remove list of tibbles from memory
  rm(list_of_pm_25_frm_tibbles)
  
  # remove big tibble from memory
  rm(big_pm_25_frm_tibble)
  
  # clear memory
  gc()

}

```


```{r functionalize the speciation}

speciator <- 
  function(speciation_file_link) {
    
    # extract the file name from the link
    speciation_zip_file_name <-
      str_extract(
        speciation_file_link,
        "daily_.+\\.zip"
        )
    
    # create rdata file name
    speciation_rdata_file_name <- 
      str_replace(
        speciation_zip_file_name,
        "zip",
        "rdata"
        )
    
     if(
      !file.exists(  # checks if tibble already exists
        file.path(
          "intermediate_data",
          speciation_rdata_file_name
          )
        )
      ) {
       
       # download the file
       file_downloader(
         desired_filename_as_string = speciation_zip_file_name,
         web_address_as_string = speciation_file_link,
         folder_as_string = "raw_data"
       )
    
       # unzip the file
       unzip(
         file.path(
           "raw_data",
           speciation_zip_file_name
           ), 
         exdir = "intermediate_data"
         )
      
       # replace ".zip" with ".csv" in list_of_speciation_zip_filenames
       speciation_csv_file_name <- 
         str_replace(
           speciation_zip_file_name, 
           "zip", 
           "csv")
      
       speciation_tibble_name <- 
         str_replace(
           speciation_zip_file_name, 
           ".zip",
           ""
         )
      
       # read .csv file into a tibble
         speciation_tibble <- 
           read_csv(
             file.path(
               "intermediate_data",
               speciation_csv_file_name
               )
             )
         
       # fix column names
       speciation_tibble <-
         column_name_fixer(
           speciation_tibble
         )
       
       # load organic carbon codes
       if (!exists("organic_carbon_codes")) {
       load(
         file = 
           file.path(
             "intermediate_data", 
             "organic_carbon_codes.rdata"
             )
         )
       }
        
       # keep only actual component measurements and necessary columns
       speciation_tibble_shrunk <- 
         speciation_tibble %>% 
         filter(parameter_code > 88100) %>% 
         filter(!(parameter_code %in% organic_carbon_codes)) %>% 
         select(
           -c(
             pollutant_standard, 
             units_of_measure, 
             aqi, 
             method_name, 
             local_site_name, 
             address, 
             county_name)
         )
       
       # rename it to its filename
       assign(
         speciation_tibble_name, 
         speciation_tibble_shrunk
       )
        
       # save the result to disk
       save(
         list = speciation_tibble_name,
         file = 
           file.path(
             "intermediate_data",
             speciation_rdata_file_name
             )
       )
       
       # delete .csv file from disk
       map(
         file.path(
           "intermediate_data",
           speciation_csv_file_name
           ),
         file.remove
         )
      
       # remove files
       rm(
         speciation_tibble, 
         speciation_tibble_shrunk)
       gc()
     }
    
    # remove files
    rm(
      speciation_zip_file_name, 
      speciation_rdata_file_name
    )
    gc()
  }

```


```{r implement speciator en masse}

# make list of speciation web addresses
speciation_files <-
  c("https://aqs.epa.gov/aqsweb/airdata/daily_SPEC_2005.zip",
    "https://aqs.epa.gov/aqsweb/airdata/daily_SPEC_2006.zip",
    "https://aqs.epa.gov/aqsweb/airdata/daily_SPEC_2007.zip",
    "https://aqs.epa.gov/aqsweb/airdata/daily_SPEC_2008.zip",
    "https://aqs.epa.gov/aqsweb/airdata/daily_SPEC_2009.zip",
    "https://aqs.epa.gov/aqsweb/airdata/daily_SPEC_2010.zip",
    "https://aqs.epa.gov/aqsweb/airdata/daily_SPEC_2011.zip",
    "https://aqs.epa.gov/aqsweb/airdata/daily_SPEC_2012.zip",
    "https://aqs.epa.gov/aqsweb/airdata/daily_SPEC_2013.zip",
    "https://aqs.epa.gov/aqsweb/airdata/daily_SPEC_2014.zip",
    "https://aqs.epa.gov/aqsweb/airdata/daily_SPEC_2015.zip")

map(
  .x = speciation_files, 
  .f = speciator
)

```


```{r combine the air pollution data files}

if(
  !file.exists(  # checks if tibble already exists
    file.path(
      "intermediate_data",
      "big_speciation_tibble.rdata"
      )
    )
  ) {
  # make list of speciation file names except the file names of the first two
  speciation_file_names_except_2005_2006 <- 
    sprintf("daily_SPEC_%d.rdata", 
            seq(2007, 2015, 1))

  # load 2005 speciation file
  load(
    file.path(
      "intermediate_data", 
      "daily_SPEC_2005.rdata"
      )
    )
  
  # load 2006 speciation file
  load(
    file.path(
      "intermediate_data", 
      "daily_SPEC_2006.rdata"
      )
    )
  
  # create the first edition of the big speciation tibble by a row bind
  big_speciation_tibble <- 
    bind_rows(
      daily_SPEC_2005, 
      daily_SPEC_2006
    )
  
  # remove the 2005 and 2006 tibbles from memory
  rm(
    daily_SPEC_2005, 
    daily_SPEC_2006)
  gc()
  
  # make a function to bind the rest of the speciation tibbles
  speciebinder <- 
    function(speciation_file_name) {
      
      # make variable of tibble name
      speciation_tibble_name <- 
        str_replace(
          speciation_file_name, 
          ".rdata",
          ""
          )
      
      # load next speciation file
      load(
        file.path(
          "intermediate_data", 
          speciation_file_name
        )
      )
      
      # bind the speciation file to the big tibble
      big_speciation_tibble <<- 
        bind_rows(  
          big_speciation_tibble, 
          eval(as.symbol(speciation_tibble_name)))
      
      # remove the speciation file and clear the memory
      rm(speciation_file_name, 
         list = speciation_tibble_name)
      gc()
      
    }
  
  # make the big speciation dataset
  speciebinder("daily_SPEC_2007.rdata")
  gc()
  speciebinder("daily_SPEC_2008.rdata")
  gc()
  speciebinder("daily_SPEC_2009.rdata")
  gc()
  speciebinder("daily_SPEC_2010.rdata")
  gc()
  speciebinder("daily_SPEC_2011.rdata")
  gc()
  speciebinder("daily_SPEC_2012.rdata")
  gc()
  speciebinder("daily_SPEC_2013.rdata")
  gc()
  speciebinder("daily_SPEC_2014.rdata")
  gc()
  speciebinder("daily_SPEC_2015.rdata")
  gc()
  
  # save the big speciation dataset
  save(
    big_speciation_tibble, 
    file = 
      file.path(
        "intermediate_data", 
        "big_speciation_tibble.rdata"
        )
  )
  
  # remove non-needed files from memory
  rm(speciation_files, 
     speciation_file_names_except_2005_2006,
     big_speciation_tibble)
  gc()
  }

```


```{r join pm25 total and speciation data}

# if(
#   !file.exists(  # checks if tibble already exists
#     file.path(
#       "intermediate_data",
#       "big_air_tibble.rdata"
#       )
#     )
#   ) {
#   
#   # load the total pm2.5 tibble
#   load(
#     file.path(
#       "intermediate_data",
#       "big_pm_25_frm_tibble.rdata"
#     )
#   )
# 
#   # load the pm2.5 speciation tibble
#   load(
#     file.path(
#       "intermediate_data",
#       "big_speciation_tibble.rdata"
#     )
#   )
# 
#   # and in the darkness bind them
#   big_air_tibble <- 
#     bind_rows(  
#       big_pm_25_frm_tibble,
#       big_speciation_tibble)
#   
#   # remove extraneous files
#   rm(big_pm_25_frm_tibble, 
#      big_speciation_tibble)
#   gc()
#   
#   # save the big tibble
#   save(
#     big_air_tibble, 
#     file = 
#       file.path(
#         "intermediate_data", 
#         "big_air_tibble.rdata"
#       ))
#   
# }

```

## demographic and ses data

```{r census variable lists}

# # view census variables
# census_variables_sf1 <- 
#   load_variables(
#     2010, 
#     "sf1", 
#     cache = TRUE
#     )
# census_variables_sf3 <- 
#   load_variables(
#     2000, 
#     "sf3", 
#     cache = TRUE
#     )
# acs_variables <- 
#   load_variables(
#     2012, 
#     "acs", 
#     cache = TRUE
#   )

# define categories for variables

# total population (SF1 P1)
# universe: total population
total_pop_sf1_p1 <-
  c("P0010001")

# hispanic or latino origin by race (SF1 P5)
# universe: total population
race_sf1_p5 <-
  sprintf("P00500%0.2d", 1:17)

# P0050001  Total population:
# P0050002    Not Hispanic or Latino:
# P0050003      White alone
# P0050004      Black or African American alone
# P0050005      American Indian and Alaska Native alone
# P0050006      Asian alone
# P0050007      Native Hawaiian and Other Pacific Islander alone
# P0050008      Some Other Race alone
# P0050009      Two or More Races
# P0050010    Hispanic or Latino:
# P0050011      White alone
# P0050012      Black or African American alone
# P0050013      American Indian and Alaska Native alone
# P0050014      Asian alone
# P0050015      Native Hawaiian and Other Pacific Islander alone
# P0050016      Some Other Race alone
# P0050017      Two or More Races

# sex by age (SF1 P12)
# universe: total population
sex_cat_sf1_p12 <-
  c("P0120002",  # male
    "P0120026")  # female

# sex by age (SF1 P12)
# universe: total population
sex_by_age_sf1_p12 <- 
  sprintf("P01200%0.2d", 1:49)

# P0120001  Total population:
# P0120002    Male:
# P0120003      Under 5 years
# P0120004      5 to 9 years
# P0120005      10 to 14 years
# P0120006      15 to 17 years
# P0120007      18 and 19 years
# P0120008      20 years
# P0120009      21 years
# P0120010      22 to 24 years
# P0120011      25 to 29 years
# P0120012      30 to 34 years
# P0120013      35 to 39 years
# P0120014      40 to 44 years
# P0120015      45 to 49 years
# P0120016      50 to 54 years
# P0120017      55 to 59 years
# P0120018      60 and 61 years
# P0120019      62 to 64 years
# P0120020      65 and 66 years
# P0120021      67 to 69 years
# P0120022      70 to 74 years
# P0120023      75 to 79 years
# P0120024      80 to 84 years
# P0120025      85 years and over
# P0120026    Female:
# P0120027      Under 5 years
# P0120028      5 to 9 years
# P0120029      10 to 14 years
# P0120030      15 to 17 years
# P0120031      18 and 19 years
# P0120032      20 years
# P0120033      21 years
# P0120034      22 to 24 years
# P0120035      25 to 29 years
# P0120036      30 to 34 years
# P0120037      35 to 39 years
# P0120038      40 to 44 years
# P0120039      45 to 49 years
# P0120040      50 to 54 years
# P0120041      55 to 59 years
# P0120042      60 and 61 years
# P0120043      62 to 64 years
# P0120044      65 and 66 years
# P0120045      67 to 69 years
# P0120046      70 to 74 years
# P0120047      75 to 79 years
# P0120048      80 to 84 years
# P0120049      85 years and over

# median age (SF1 P13)
# universe: total population
age_median_sf1_p13 <- 
  "P0130001"

# occupancy status
# universe: housing units
# 1 total, 2 occupied, 3 vacant
occupancy_sf1_h3 <-
  sprintf("H003000%d", 1:3)

# housing tenure (SF1 H4)
# universe: occupied housing units
# 1 total, 2 owned w/ a mortgage or loan, 3 owned free and clear, 4 renter-occupied
housing_tenure_sf1_h4 <-  
  sprintf("H004000%d", 1:4)

# population in occupied housing units by tenure
# universe: population in occupied housing units
housing_tenure_people_sf1_h11 <- 
  c("H0110001",  # total population in occupied housing units
    "H0110002",  # owned with a mortgage or a loan 
    "H0110003",  # owned free and clear
    "H0110004")  # renter-occupied

```


```{r acs variable lists}

# educational attainment for the population 25 years and over
# universe: population 25 years and over
education_cat_acs_b15003 <- 
  c("B15003_001",  # total
    "B15003_002",  # no schooling completed
    "B15003_003",  # nursery school
    "B15003_004",  # kindergarten
    "B15003_005",  # 1st grade
    "B15003_006",  # 2nd grade
    "B15003_007",  # 3rd grade
    "B15003_008",  # 4th grade
    "B15003_009",  # 5th grade
    "B15003_010",  # 6th grade
    "B15003_011",  # 7th grade
    "B15003_012",  # 8th grade
    "B15003_013",  # 9th grade
    "B15003_014",  # 10th grade
    "B15003_015",  # 11th grade
    "B15003_016",  # 12th grade
    "B15003_017",  # regular high school diploma
    "B15003_018",  # GED or alternative credential
    "B15003_019",  # some college, less than 1 year
    "B15003_020",  # some college, 1 or more years, no degree
    "B15003_021",  # associate's degree
    "B15003_022",  # bachelor's degree
    "B15003_023",  # master's degree
    "B15003_024",  # professional school degree
    "B15003_025")  # doctorate degree

# ratio of income to poverty level in the past 12 months
# universe: population for whom poverty status is determined
poverty_ratio_cat_c17002 <-
  c("C17002_001",  # total
    "C17002_002",  # under .50
    "C17002_003",  # .50 to .99
    "C17002_004",  # 1.00 to 1.24
    "C17002_005",  # 1.25 to 1.49
    "C17002_006",  # 1.50 to 1.84
    "C17002_007",  # 1.85 to 1.99
    "C17002_008")  # 2.00 and over

# household income in the past 12 months (in 2012 inflation-adjusted dollars)
# universe: households
income_house_cat_b19001 <-
  c("B19001_001",  # total
    "B19001_002",  # less than $10,000
    "B19001_003",  # $10,000 to $14,999
    "B19001_004",  # $15,000 to $19,999
    "B19001_005",  # $20,000 to $24,999
    "B19001_006",  # $25,000 to $29,999
    "B19001_007",  # $30,000 to $34,999
    "B19001_008",  # $35,000 to $39,999
    "B19001_009",  # $40,000 to $44,999
    "B19001_010",  # $45,000 to $49,999
    "B19001_011",  # $50,000 to $59,999
    "B19001_012",  # $60,000 to $74,999
    "B19001_013",  # $75,000 to $99,999
    "B19001_014",  # $100,000 to $124,999
    "B19001_015",  # $125,000 to $149,999
    "B19001_016",  # $150,000 to $199,999
    "B19001_017")  # $200,000 or more

# median household income in the past 12 months (in 2012 inflation-adjusted dollars)
# universe: households
income_house_median_b19013 <-
  c("B19013_001")

# sex by earnings in the past 12 months (in 2012 inflation-adjusted dollars) for the population 16 years and over with earnings in the past 12 months
# universe: population 16 years and over with earnings
earnings_sex_cat_b20001 <-
  c("B20001_001",  # total
    "B20001_002",  # male
    "B20001_003",  # $1 to $2,499 or loss
    "B20001_004",  # $2,500 to $4,999
    "B20001_005",  # $5,000 to $7,499
    "B20001_006",  # $7,500 to $9,999
    "B20001_007",  # $10,000 to $12,499
    "B20001_008",  # $12,500 to $14,999
    "B20001_009",  # $15,000 to $17,499
    "B20001_010",  # $17,500 to $19,999
    "B20001_011",  # $20,000 to $22,499
    "B20001_012",  # $22,500 to $24,999
    "B20001_013",  # $25,000 to $29,999
    "B20001_014",  # $30,000 to $34,999
    "B20001_015",  # $35,000 to $39,999
    "B20001_016",  # $40,000 to $44,999
    "B20001_017",  # $45,000 to $49,999
    "B20001_018",  # $50,000 to $54,999
    "B20001_019",  # $55,000 to $64,999
    "B20001_020",  # $65,000 to $74,999
    "B20001_021",  # $75,000 to $99,999
    "B20001_022",  # $100,000 or more
    "B20001_023",  # Female:
    "B20001_024",  # $1 to $2,499 or loss
    "B20001_025",  # $2,500 to $4,999
    "B20001_026",  # $5,000 to $7,499
    "B20001_027",  # $7,500 to $9,999
    "B20001_028",  # $10,000 to $12,499
    "B20001_029",  # $12,500 to $14,999
    "B20001_030",  # $15,000 to $17,499
    "B20001_031",  # $17,500 to $19,999
    "B20001_032",  # $20,000 to $22,499
    "B20001_033",  # $22,500 to $24,999
    "B20001_034",  # $25,000 to $29,999
    "B20001_035",  # $30,000 to $34,999
    "B20001_036",  # $35,000 to $39,999
    "B20001_037",  # $40,000 to $44,999
    "B20001_038",  # $45,000 to $49,999
    "B20001_039",  # $50,000 to $54,999
    "B20001_040",  # $55,000 to $64,999
    "B20001_041",  # $65,000 to $74,999
    "B20001_042",  # $75,000 to $99,999
    "B20001_043")  # $100,000 or more

# median earnings in the past 12 months (in 2012 inflation-adjusted dollars) by sex for the population 16 years and over with earnings in the past 12 months
# universe: population 16 years and over with earnings
earnings_median_b20002 <-
  c("B20002_001",  # total
    "B20002_002",  # male
    "B20002_003")  # female

# employment status for the population 16 years and over
# universe: population 16 years and over
employment_cat_b23025 <-  # divide 5 by 3
  c("B23025_001",  # total
    "B23025_002",    # in labor force
    "B23025_003",      # civilian labor force
    "B23025_004",        # employed
    "B23025_005",        # unemployed
    "B23025_006",      # armed forces
    "B23025_007")    # not in labor force
  
# value
# universe: owner-occupied housing units
home_value_cat_b25075 <-
  c("B25075_001",  # total
    "B25075_002",  # less than $10,000
    "B25075_003",  # $10,000 to $14,999
    "B25075_004",  # $15,000 to $19,999
    "B25075_005",  # $20,000 to $24,999
    "B25075_006",  # $25,000 to $29,999
    "B25075_007",  # $30,000 to $34,999
    "B25075_008",  # $35,000 to $39,999
    "B25075_009",  # $40,000 to $49,999
    "B25075_010",  # $50,000 to $59,999
    "B25075_011",  # $60,000 to $69,999
    "B25075_012",  # $70,000 to $79,999
    "B25075_013",  # $80,000 to $89,999
    "B25075_014",  # $90,000 to $99,999
    "B25075_015",  # $100,000 to $124,999
    "B25075_016",  # $125,000 to $149,999
    "B25075_017",  # $150,000 to $174,999
    "B25075_018",  # $175,000 to $199,999
    "B25075_019",  # $200,000 to $249,999
    "B25075_020",  # $250,000 to $299,999
    "B25075_021",  # $300,000 to $399,999
    "B25075_022",  # $400,000 to $499,999
    "B25075_023",  # $500,000 to $749,999
    "B25075_024",  # $750,000 to $999,999
    "B25075_025")  # $1,000,000 or more

# median value (dollars)
# universe: owner-occupied housing units
home_value_median <-
  c("B25077_001")  # median value (dollars)

# types of health insurance coverage by age
# universe: civilian noninstitutionalized population
health_insurance_cat_c27010 <-
  c("C27010_001",  # total
    "C27010_002",    # under 18 years
    "C27010_003",      # with private health insurance only
    "C27010_004",      # with public coverage only
    "C27010_005",      # with both private and public coverage
    "C27010_006",      # no health insurance coverage
    "C27010_007",    # 18 to 34 years
    "C27010_008",      # with private health insurance only
    "C27010_009",      # with public coverage only
    "C27010_010",      # with both private and public coverage
    "C27010_011",      # no health insurance coverage
    "C27010_012",    # 35 to 64 years
    "C27010_013",      # with private health insurance only
    "C27010_014",      # with public coverage only
    "C27010_015",      # with both private and public coverage
    "C27010_016",      # no health insurance coverage
    "C27010_017",    # 65 years and over
    "C27010_018",      # with private health insurance only
    "C27010_019",      # with public coverage only
    "C27010_020",      # with both private and public coverage
    "C27010_021")      # no health insurance coverage

# household language by households in which no one 14 and over speaks english only or speaks a language other than english at home and speaks english "very well"
# universe: households
ling_iso <-
  c("B16002_001",  # total
    "B16002_002",    # English only
    "B16002_003",    # Spanish:
    "B16002_004",      # No one 14 and over speaks English only or speaks English "very well"
    "B16002_005",      # At least one person 14 and over speaks English only or speaks English "very well"
    "B16002_006",    # Other Indo-European languages:
    "B16002_007",      # No one 14 and over speaks English only or speaks English "very well"
    "B16002_008",      # At least one person 14 and over speaks English only or speaks English "very well"
    "B16002_009",    # Asian and Pacific Island languages:
    "B16002_010",      # No one 14 and over speaks English only or speaks English "very well"
    "B16002_011",      # At least one person 14 and over speaks English only or speaks English "very well"
    "B16002_012",    # Other languages: 
    "B16002_013",      # No one 14 and over speaks English only or speaks English "very well"
    "B16002_014")     # At least one person 14 and over speaks English only or speaks English "very well"

```


```{r american community survey data}

if(
  !file.exists(  # checks if tibble already exists
    file.path(
      "intermediate_data",
      "total_pop_tibble_list.rdata"
      )
    )
  ) {

  # list of dataframes for states
  total_pop_tibble_list <- 
    list()
  
  # al pop
  total_pop_tibble_list[["AL"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "AL", 
      year = 2012)
  
  total_pop_tibble_list[["AK"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "AK", 
      year = 2012)
  
  total_pop_tibble_list[["AZ"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "AZ", 
      year = 2012)
  
  total_pop_tibble_list[["AR"]] <- 
      get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "AR", 
      year = 2012)
  
  total_pop_tibble_list[["CA"]] <- 
      get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "CA", 
      year = 2012)
  
  total_pop_tibble_list[["CO"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "CO", 
      year = 2012)
  
  total_pop_tibble_list[["CT"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "CT", 
      year = 2012)
  
  total_pop_tibble_list[["DE"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "DE", 
      year = 2012)
  
  total_pop_tibble_list[["FL"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "FL", 
      year = 2012)
  
  total_pop_tibble_list[["GA"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "GA", 
      year = 2012)
  
  total_pop_tibble_list[["HI"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "HI", 
      year = 2012)
  
  total_pop_tibble_list[["ID"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "ID", 
      year = 2012)
  
  total_pop_tibble_list[["IL"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "IL", 
      year = 2012)
  
  total_pop_tibble_list[["IN"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "IN", 
      year = 2012)
  
  total_pop_tibble_list[["IA"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "IA", 
      year = 2012)
  
  total_pop_tibble_list[["KS"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "KS", 
      year = 2012)
  
  total_pop_tibble_list[["KY"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "KY", 
      year = 2012)
  
  total_pop_tibble_list[["LA"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "LA", 
      year = 2012)
  
  total_pop_tibble_list[["ME"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "ME", 
      year = 2012)
  
  total_pop_tibble_list[["MD"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "MD", 
      year = 2012)
  
  total_pop_tibble_list[["MA"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "MA", 
      year = 2012)
  
  total_pop_tibble_list[["MI"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "MI", 
      year = 2012)
  
  total_pop_tibble_list[["MN"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "MN", 
      year = 2012)
  
  total_pop_tibble_list[["MS"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "MS", 
      year = 2012)
  
  total_pop_tibble_list[["MO"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "MO", 
      year = 2012)
  
  total_pop_tibble_list[["MT"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "MT", 
      year = 2012)
  
  total_pop_tibble_list[["NE"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "NE", 
      year = 2012)
  
  total_pop_tibble_list[["NV"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "NV", 
      year = 2012)
  
  total_pop_tibble_list[["NH"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "NH", 
      year = 2012)
  
  total_pop_tibble_list[["NJ"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "NJ", 
      year = 2012)
  
  total_pop_tibble_list[["NM"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "NM", 
      year = 2012)
  
  total_pop_tibble_list[["NY"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "NY", 
      year = 2012)
  
  total_pop_tibble_list[["NC"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "NC", 
      year = 2012)
  
  total_pop_tibble_list[["ND"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "ND", 
      year = 2012)
  
  total_pop_tibble_list[["OH"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "OH", 
      year = 2012)
  
  total_pop_tibble_list[["OK"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "OK", 
      year = 2012)
  
  total_pop_tibble_list[["OR"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "OR", 
      year = 2012)
  
  total_pop_tibble_list[["PA"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "PA", 
      year = 2012)
  
  total_pop_tibble_list[["RI"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "RI", 
      year = 2012)
  
  total_pop_tibble_list[["SC"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "SC", 
      year = 2012)
  
  total_pop_tibble_list[["SD"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "SD", 
      year = 2012)
  
  total_pop_tibble_list[["TN"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "TN", 
      year = 2012)
  
  total_pop_tibble_list[["TX"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "TX", 
      year = 2012)
  
  total_pop_tibble_list[["UT"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "UT", 
      year = 2012)
  
  total_pop_tibble_list[["VT"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "VT", 
      year = 2012)
  
  total_pop_tibble_list[["VA"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "VA", 
      year = 2012)
  
  total_pop_tibble_list[["WA"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "WA", 
      year = 2012)
  
  total_pop_tibble_list[["WV"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "WV", 
      year = 2012)
  
  total_pop_tibble_list[["WI"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "WI", 
      year = 2012)
  
  total_pop_tibble_list[["WY"]] <- 
    get_acs(
      geography = "tract", 
      variables = "B01003_001", 
      state = "WY", 
      year = 2012)
  
  save(
    total_pop_tibble_list, 
    file = 
      file.path(
        "intermediate_data", 
        "total_pop_tibble_list.rdata"
      )
    )
  
  # rm(total_pop_tibble_list)
  # gc()
}    

```


## clean air pollution data


